<?php
throw new Exception();
-----
{main}:
	encounters: [Exception]